"""Type stubs for clinglite._core (nanobind extension module)."""

from __future__ import annotations
from enum import Enum
from typing import Callable

class ExecResult(Enum):
    Success: ExecResult
    Failure: ExecResult
    MoreInputExpected: ExecResult

class EntrypointArgStyle(Enum):
    MutableArgv: EntrypointArgStyle
    ConstArgv: EntrypointArgStyle
    NoArgs: EntrypointArgStyle

class Environment:
    def __init__(self, argv0: str | None = None) -> None: ...
    def crash_recovery_enabled(self) -> bool: ...
    @staticmethod
    def version() -> str: ...
    def __enter__(self) -> Environment: ...
    def __exit__(self, *args: object) -> None: ...

class Value:
    def __init__(self) -> None: ...
    @property
    def valid(self) -> bool: ...
    @property
    def has_value(self) -> bool: ...
    def as_int(self) -> int: ...
    def as_uint(self) -> int: ...
    def as_double(self) -> float: ...
    def as_ptr(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __bool__(self) -> bool: ...

class Options:
    def __init__(self) -> None: ...
    args: list[str]
    include_paths: list[str]
    compiler_flags: list[str]
    llvm_dir: str
    pch_path: str

class CompletionResult:
    def __init__(self) -> None: ...
    @property
    def completions(self) -> list[str]: ...
    @property
    def prefix(self) -> str: ...
    @property
    def match_start(self) -> int: ...
    @property
    def match_end(self) -> int: ...

class Interpreter:
    def __init__(self, opts: Options) -> None: ...
    @property
    def valid(self) -> bool: ...
    def execute(self, code: str) -> Value | None: ...
    def execute_raw(self, code: str) -> ExecResult: ...
    def execute_with_value(self, code: str) -> tuple[ExecResult, Value]: ...
    def execute_safe(self, code: str) -> tuple[ExecResult, Value, int]: ...
    def add_include_path(self, path: str) -> None: ...
    def include_header(self, header: str) -> bool: ...
    def load_file(self, path: str) -> ExecResult: ...
    def declare_file(self, path: str) -> ExecResult: ...
    def load_file_namespaced(self, path: str, ns: str) -> ExecResult: ...
    def add_virtual_file(self, path: str, content: str) -> None: ...
    def load_library(self, path: str) -> ExecResult: ...
    def process_line(self, line: str) -> tuple[int, ExecResult, int]: ...
    def cancel_continuation(self) -> None: ...
    def get_symbol_address(self, mangled_name: str) -> tuple[int, bool]: ...
    def code_complete(self, line: str, cursor: int) -> CompletionResult: ...
    def undo(self, n: int = 1) -> int: ...
    @property
    def undoable_count(self) -> int: ...
    def set_output_callback(self, callback: Callable[[str], None]) -> None: ...
    def clear_output_callback(self) -> None: ...
    def set_error_callback(self, callback: Callable[[str], None]) -> None: ...
    def clear_error_callback(self) -> None: ...
    def generate_pch(self, output_path: str) -> bool: ...
    def enumerate_declarations(self, source_filter: str = "") -> list[str]: ...
    @staticmethod
    def enumerate_library_exports(library_path: str) -> list[str]: ...

class Session:
    def __init__(self, interp: Interpreter) -> None: ...
    def eval_snippet(self, code: str) -> None: ...
    def eval_snippet_safe(self, code: str) -> tuple[bool, str]: ...
    def eval_expr(self, expr: str) -> Value: ...
    def process_line(self, line: str) -> tuple[int, ExecResult, int]: ...
    def clear(self) -> None: ...
    @property
    def interp(self) -> Interpreter: ...

class EntrypointCandidate:
    def __init__(self) -> None: ...
    label: str
    symbol: str
    signature: str
    arg_style: EntrypointArgStyle
    returns_value: bool

class FileExecOptions:
    def __init__(self) -> None: ...
    args: list[str]
    entrypoint_groups: list[list[EntrypointCandidate]]
    allow_no_entrypoint: bool

class ScriptRunnerStatus:
    def __init__(self) -> None: ...
    @property
    def last_file_executed(self) -> str: ...
    @property
    def last_file_namespace(self) -> str: ...
    @property
    def last_entrypoint_chosen(self) -> str: ...
    @property
    def last_error(self) -> str: ...

class ScriptRunner:
    def __init__(self, session: Session) -> None: ...
    def set_namespace_prefix(self, prefix: str) -> None: ...
    def set_runtime_namespace(self, ns: str) -> None: ...
    def compile_file(self, file: str, namespace_: str | None = None) -> None: ...
    def exec_file(self, file: str, options: FileExecOptions = ...) -> Value: ...
    @property
    def status(self) -> ScriptRunnerStatus: ...
    def reset_status(self) -> None: ...
    @property
    def session(self) -> Session: ...

def standard_main_candidates() -> list[EntrypointCandidate]: ...
def cpp_string_literal(s: str) -> str: ...
def escape_path(path: str) -> str: ...
